accent = "#AD9980"
cursor = "#b76e79"
foreground = "#35302a"
background = "#F5E6D3"
selection_foreground = "#35302a"
selection_background = "#B76e79"

color0 = "#F5E6D3"
color1 = "#a02b16"
color2 = "#b76e79"
color3 = "#644535"
color4 = "#AD9980"
color5 = "#b76e81"
color6 = "#3b3b28"
color7 = "#DEA193"
color8 = "#6F4C3E"
color9 = "#a02b16"
color10 = "#b76e79"
color11 = "#694C45"
color12 = "#AD9980"
color13 = "#b76e81"
color14 = "#3b3b28"
color15 = "#DEA193"
